"""empty message

Revision ID: 06c83605b929
Revises: 11ab0538b4e5
Create Date: 2025-02-07 18:03:10.260329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06c83605b929'
down_revision = '11ab0538b4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('event_theme', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('event_color', sa.String(length=40), nullable=False))
        batch_op.alter_column('event_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', mysql.TIME(), nullable=False))
        batch_op.alter_column('event_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('event_color')
        batch_op.drop_column('event_theme')
        batch_op.drop_column('food_time')

    # ### end Alembic commands ###
