"""empty message

Revision ID: 11ab0538b4e5
Revises: 200629ecc66d
Create Date: 2025-02-07 17:31:14.102973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ab0538b4e5'
down_revision = '200629ecc66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['package_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
