"""empty message

Revision ID: 200629ecc66d
Revises: 
Create Date: 2025-02-07 17:14:50.889129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '200629ecc66d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'event_details', ['event_id'], ['event_id'])
        batch_op.drop_column('package_id')

    with op.batch_alter_table('event_details', schema=None) as batch_op:
        batch_op.drop_constraint('event_details_ibfk_1', type_='foreignkey')
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('event_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('event_details_ibfk_1', 'bookings', ['booking_id'], ['booking_id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
