"""empty message

Revision ID: 5e54072550c6
Revises: 9125aea9540f
Create Date: 2025-02-07 22:10:50.399095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e54072550c6'
down_revision = '9125aea9540f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'payments', ['payment_id'], ['payment_id'])
        batch_op.drop_column('is_paid')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_ibfk_1', type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payments_ibfk_1', 'bookings', ['booking_id'], ['booking_id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
