"""empty message

Revision ID: 6cff8ec9b539
Revises: 
Create Date: 2025-01-27 20:36:32.441162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cff8ec9b539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('middlename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('suffix', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suffix')
        batch_op.drop_column('lastname')
        batch_op.drop_column('middlename')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
