"""empty message

Revision ID: 946666631351
Revises: bbaafe78cb07
Create Date: 2025-02-08 00:52:45.158375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '946666631351'
down_revision = 'bbaafe78cb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('paid_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payments_ibfk_1', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('paid_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))

    # ### end Alembic commands ###
