"""empty message

Revision ID: a8db6025d38f
Revises: efef9533f9d7
Create Date: 2025-02-14 03:39:47.283821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8db6025d38f'
down_revision = 'efef9533f9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_theme', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('event_theme')
        batch_op.drop_column('menu_quantity')

    # ### end Alembic commands ###
