"""empty message

Revision ID: bbaafe78cb07
Revises: 5e54072550c6
Create Date: 2025-02-07 22:25:47.894277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbaafe78cb07'
down_revision = '5e54072550c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed'), nullable=False))
        batch_op.add_column(sa.Column('reference_no', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['reference_no'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reference_no')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('amount')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###
